### ISSUE TITLE
“Read More” to Spa Review functionality to activity feed

### ISSUE THREAD

**Issue by miler350** [The-Wildfyre-Group/spatravlr#4]
The same functionality as requested in the previous issue but on the 
"/activities" page. On the "activities" page, there is an activity feed that will auto-populate after various actions on the site. After a review, it will appear here.

In the cases where the review is long, we will also need "Read more" on this page.

This page will use the activities layout.

A reference commit: http://bit.ly/1BVZ3i3

**Comment by dipakgror** [comment]
Have fixed please see commit https://github.com/The-Wildfyre-Group/spatravlr/commit/3cee8ddd4367db7c268de9f65512bd9865c6b7b1
